### PR TITLE
WL-350 i18n support for recomender xblock

### PR DESCRIPTION
**Pull request by asadiqbal08**
[WL-350](https://openedx.atlassian.net/browse/WL-350)

screen shot 2016-05-27 at 12 24 59 pm

### CODE REVIEW

**Comment by mattdrayer** [comment]
LGTM -- 👍 -- @pmitros can you review and merge?  Also we'll need a release tag to be created.

**Comment by pmitros** [comment]
@swdanielli Looks good to me, but I'm less familiar with the code than you are. Would you mind reviewing, and if there are no issues, hitting the merge button?

**Comment by swdanielli** [comment]
👍

**Comment by mattdrayer** [comment]
great, thanks guys!  can you also please [create a new release](https://github.com/pmitros/RecommenderXBlock/releases)?

**Comment by swdanielli** [comment]
@pmitros  could you do the tagging for me? I am not sure about the current rules.

**Comment by mattdrayer** [comment]
@pmitros any chance you can get to that release tag today?  I'd like to build a new edx-platform stage AMI tomorrow with the updated reference.

**Comment by pmitros** [comment]
@mattdrayer On it right now.

**Comment by pmitros** [comment]
@mattdrayer Tagged as v1.0

**Comment by mattdrayer** [comment]
great, thank you!!!  Ready to go, @asadiqbal08 😄

**Pull request merged**
